name: inventori
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "img/fotoa.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "img/fotoa.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "img/fotoa.jpg"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - img/fotoa.jpg
    - img/fotob.jpg
    - img/fotoc.jpg
